language: python
python:
    - "3.5"
cache:
  pip: true

env:
  - TOXENV=py35

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database leadbook;' -U postgres


script: python manage.py test

notifications:
  slack: techproitservices:XsEF41X8AaQfMPg9I5XL10Gr
