language: python
python:
    - "3.5"
cache:
  pip: true

env:
  - TOXENV=py35

install:
  - pip install tox

script: python manage.py test

notifications:
  slack: techproitservices:XsEF41X8AaQfMPg9I5XL10Gr
