language: python
python:
    - "3.5"
cache:
  pip: true
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

env:
  - TOXENV=py35
  - SECRET_KEY=0d77b6b3e461830202b0338b8e47fcd1
  - DATABASE_HOST=localhost
  - DATABASE_NAME=leadbook
  - DATABASE_PASSWORD=
  - DATABASE_PORT=
  - DATABASE_USER=postgres
  - SENDGRID_API_KEY=

install:
  - pip install -r requirements.txt
  - yarn install

services:
  - postgresql

before_script:
  - psql -c 'create database leadbook;' -U postgres

script:
  - python manage.py migrate
  - python manage.py test
  - yarn test

notifications:
  slack: techproitservices:XsEF41X8AaQfMPg9I5XL10Gr
