export const USER_SIGN_IN  = 'USER_SIGN_IN';
export const USER_ACCOUNT_ACTIVATED = 'USER_ACCOUNT_ACTIVATED';
export const USER_ACCOUNT_ACTIVATION_ERROR = 'USER_ACCOUNT_ACTIVATION_ERROR';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
