# Generated by Django 2.1.5 on 2019-01-11 18:29

from django.db import migrations
from leadbook.companies.fixtures import companies

def create_data(apps, schema_editor):
    Customer = apps.get_model('companies', 'Company')

    for company in companies:
        Customer(name=company.get('name'), address=company.get('address'), phone=company.get('phone'), logo=company.get('logo')).save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
