companies = [
    {
        'name': 'Destiny Realty Solutions',
        'building': 'One Raffles Place Tower 1',
        'address_line_one': '71 KAMPONG BAHRU ROAD',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '169373',
        'province': '',
        'industry': 'Real Estate',
        'phone': '+65 6325 2633',
        'logo': 'http://acmelogos.com/images/logo-1.svg'
    },
    {
        'name': 'Weenie Beenie',
        'building': 'Republic Plaza',
        'address_line_one': '31 Tampines Ave 4',
        'building': '#05-01 OCBC Tampines Centre 1',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '529680',
        'province': '',
        'industry': '',
        'phone': '+65 6424 6000',
        'logo': 'http://acmelogos.com/images/logo-2.svg'
    },
    {
        'name': 'Video Concepts',
        'building': '#30-01 Hitachi Tower',
        'address_line_one': '16 Collyer Quay',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '049318',
        'province': '',
        'industry': '',
        'phone': '+65 6587 0038',
        'logo': 'http://acmelogos.com/images/logo-3.svg'
    },
    {
        'name': 'Gas Depot',
        'building': 'United Overseas Bank Plaza One',
        'address_line_one': '69 Choa Chu Kang Loop #02-12',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '689672',
        'province': '',
        'industry': '',
        'phone': '+65 6225 5154',
        'logo': 'http://acmelogos.com/images/logo-4.svg'
    },
    {
        'name': 'Virgin Megastores',
        'building': '03-02 Bukit Timah Shopping Centre',
        'address_line_one': '170 Upper Bukit Timah Road',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '588179',
        'province': '',
        'industry': '',
        'phone': '+6562253343',
        'logo': 'http://acmelogos.com/images/logo-5.svg'
    },
    {
        'name': 'Stop N Shop',
        'building': 'Capital Tower',
        'address_line_one': '9 Pioneer Sector 1',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '628421',
        'province': '',
        'industry': '',
        'phone': '+65 6532 7765',
        'logo': 'http://acmelogos.com/images/logo-6.svg'
    },
    {
        'name': 'Old China Stores',
        'building': '21-06 Orchard Tower',
        'address_line_one': '400 Orchard Road',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '238875',
        'province': '',
        'industry': '',
        'phone': '+65 6532 6859',
        'logo': 'http://acmelogos.com/images/logo-7.svg'
    },
    {
        'name': 'Magik Gray',
        'building': 'Blk 89',
        'address_line_one': '4 Bedok Nth St ',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '460089',
        'province': '',
        'industry': '',
        'phone': '+65 6747 2871',
        'logo': 'http://acmelogos.com/images/logo-8.svg'
    },
    {
        'name': 'Mansmann',
        'building': 'Altez',
        'address_line_one': '21 Gul Ave, 629661',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '',
        'province': '',
        'industry': '',
        'phone': '+65 6749 5211',
        'logo': 'http://acmelogos.com/images/logo-9.svg'
    },
    {
        'name': 'Borders Books',
        'building': '#05-02 Certis Cisco Centre',
        'address_line_one': '20 Jalan Afifi',
        'address_line_two': '',
        'city': 'Singapore',
        'country': 'Singapore',
        'postcode': '409179',
        'province': '',
        'industry': '',
        'phone': '+65 6260 5473',
        'logo': 'http://acmelogos.com/images/logo-10.svg'
    }
]
