export const FOLLOW_COMPANY = 'FOLLOW_COMPANY';
export const UNFOLLOW_COMPANY = 'UNFOLLOW_COMPANY';
export const GET_USER_FAVOURITES_SUCCESS = 'GET_USER_FAVOURITES_SUCCESS';
export const GET_USER_FAVOURITES_FAILURE = 'GET_USER_FAVOURITES_FAILURE';
