# Generated by Django 2.1.5 on 2019-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190116_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
