export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
export const GET_USER_FAVOURITES_SUCCESS = 'GET_USER_FAVOURITES_SUCCESS';
export const GET_USER_FAVOURITES = 'GET_USER_FAVOURITES';
